export const merchants = [
    { id: 1, title: "미즈케어 솔루션 2", url: "https://replyalba.com/pt/Y1PHVwO7GO" },
    { id: 2, title: "CR-5", url: "https://replyalba.com/pt/JNyIgk9t32" },
    { id: 3, title: "MS-II PLUS", url: "https://replyalba.com/pt/IGBX5btayE" },
    { id: 4, title: "공후하결", url: "https://replyalba.com/pt/UKfoQbTwGI" },
    { id: 5, title: "레이디큐어 솔루션", url: "https://replyalba.com/pt/WsdU9oMhje" },
    { id: 6, title: "레이디큐어 솔루션 2", url: "https://replyalba.com/pt/z6pRyceT7w" },
    { id: 7, title: "미즈케어 솔루션", url: "https://replyalba.com/pt/N0cKnHbm9V" },
    { id: 8, title: "미즈케어 솔루션 3", url: "https://replyalba.com/pt/DU4eJfMd1j" },
    { id: 9, title: "미즈케어 솔루션 4", url: "https://replyalba.com/pt/SoLJ7OMizy" },
    { id: 10, title: "미즈케어 솔루션 5", url: "https://replyalba.com/pt/Phjrq2zsy8" },
    { id: 11, title: "미즈케어 솔루션 6", url: "https://replyalba.com/pt/MbTJlgNLg8" },
    { id: 12, title: "미즈케어 솔루션 7", url: "https://replyalba.com/pt/GnNKelUPTQ" },
    { id: 13, title: "미즈케어 여궁", url: "https://replyalba.com/pt/WeWtmEo70h" },
    { id: 14, title: "바스트핏 솔루션", url: "https://replyalba.com/pt/MNGGagfIeF" },
    { id: 15, title: "베리얀", url: "https://replyalba.com/pt/NGi7kc77mF" },
    { id: 16, title: "스템벨", url: "https://replyalba.com/pt/yBXZ7Kddui" },
    { id: 17, title: "스템벨 자생력 앰플", url: "https://replyalba.com/pt/CzCyUNUG4o" },
    { id: 18, title: "스템엔셀 미미셀 시그니처", url: "https://replyalba.com/pt/Rzqo5tlz9p" },
    { id: 19, title: "여궁골드", url: "https://replyalba.com/pt/Z1IJI9rY2c" },
    { id: 20, title: "여궁닥터", url: "https://replyalba.com/pt/IlnAem4ygW" },
    { id: 21, title: "여궁화이트", url: "https://replyalba.com/pt/SNLg3ILPbd" },
    { id: 22, title: "올리모아", url: "https://replyalba.com/pt/C7qCzRVOZ8" },
    { id: 23, title: "올리모아 2", url: "https://replyalba.com/pt/yN552PODWx" },
    { id: 24, title: "우먼시크릿", url: "https://replyalba.com/pt/YfcVFCdD21" },
    { id: 25, title: "우먼시크릿2", url: "https://replyalba.com/pt/xWHMHU09mP" },
    { id: 26, title: "우먼시크릿3", url: "https://replyalba.com/pt/LAiSP6X1ij" },
    { id: 27, title: "우먼시크릿4", url: "https://replyalba.com/pt/EkShEr1oPs" },
    { id: 28, title: "우먼시크릿5", url: "https://replyalba.com/pt/WSueAH6gko" },
    { id: 29, title: "천수애진", url: "https://replyalba.com/pt/SanlazetIb" },
    { id: 30, title: "천수애진2", url: "https://replyalba.com/pt/PkcJmotCli" },
    { id: 31, title: "천수윤진", url: "https://replyalba.com/pt/ILAPhWg9Zx" },
    { id: 32, title: "천수윤진2", url: "https://replyalba.com/pt/Sxw8G15GMU" },
];
