export const merchants = [
    { id: 1, title: "미즈케어 솔루션 2", url: "https://replyalba.com/pt/Y1PHVwO7GO", subtitle: "부부관계 개선, 다시 시작하는 신혼 라이프" },
    { id: 2, title: "CR-5", url: "https://replyalba.com/pt/JNyIgk9t32", subtitle: "주름·기미·잡티 고민 한 번에 해결하세요" },
    { id: 3, title: "MS-II PLUS", url: "https://replyalba.com/pt/IGBX5btayE", subtitle: "세월의 흔적을 지우는 고기능성 스킨케어" },
    { id: 4, title: "공후하결", url: "https://replyalba.com/pt/UKfoQbTwGI", subtitle: "피부 근본부터 채우는 프리미엄 영양 케어" },
    { id: 5, title: "레이디큐어 솔루션", url: "https://replyalba.com/pt/WsdU9oMhje", subtitle: "여성만의 말 못할 고민, 근본부터 케어" },
    { id: 6, title: "레이디큐어 솔루션 2", url: "https://replyalba.com/pt/z6pRyceT7w", subtitle: "더 당당해지는 나를 위한 시크릿 솔루션" },
    { id: 7, title: "미즈케어 솔루션", url: "https://replyalba.com/pt/N0cKnHbm9V", subtitle: "여성 속깊은 고민 해결, 자신감을 되찾으세요" },
    { id: 8, title: "미즈케어 솔루션 3", url: "https://replyalba.com/pt/DU4eJfMd1j", subtitle: "하루 10분 투자로 달라지는 여성 에너지" },
    { id: 9, title: "미즈케어 솔루션 4", url: "https://replyalba.com/pt/SoLJ7OMizy", subtitle: "수술 없이 안전하게 관리하는 여성 건강" },
    { id: 10, title: "미즈케어 솔루션 5", url: "https://replyalba.com/pt/Phjrq2zsy8", subtitle: "행복한 부부생활을 위한 최상의 선택" },
    { id: 11, title: "미즈케어 솔루션 6", url: "https://replyalba.com/pt/MbTJlgNLg8", subtitle: "출산 후 늘어진 근육, 다시 탄탄하게" },
    { id: 12, title: "미즈케어 솔루션 7", url: "https://replyalba.com/pt/GnNKelUPTQ", subtitle: "건조함과 불편함을 한 번에 해결하세요" },
    { id: 13, title: "미즈케어 여궁", url: "https://replyalba.com/pt/WeWtmEo70h", subtitle: "질 건강과 수축력을 동시에 집중 케어" },
    { id: 14, title: "바스트핏 솔루션", url: "https://replyalba.com/pt/MNGGagfIeF", subtitle: "자연스럽게 차오르는 바스트 볼륨 자신감" },
    { id: 15, title: "베리얀", url: "https://replyalba.com/pt/NGi7kc77mF", subtitle: "집에서 간편하게 하는 여성 근육 강화 운동" },
    { id: 16, title: "스템벨", url: "https://replyalba.com/pt/yBXZ7Kddui", subtitle: "인체 줄기세포 배양액으로 되찾는 자생력" },
    { id: 17, title: "스템벨 자생력 앰플", url: "https://replyalba.com/pt/CzCyUNUG4o", subtitle: "피부 속부터 차오르는 프리미엄 광채 에너지" },
    { id: 18, title: "스템엔셀 미미셀 시그니처", url: "https://replyalba.com/pt/Rzqo5tlz9p", subtitle: "피부 시간을 되돌리는 줄기세포 과학적 관리" },
    { id: 19, title: "여궁골드", url: "https://replyalba.com/pt/Z1IJI9rY2c", subtitle: "여성 생애 주기별 맞춤 솔루션 제공" },
    { id: 20, title: "여궁닥터", url: "https://replyalba.com/pt/IlnAem4ygW", subtitle: "민감한 부위의 냄새와 가려움을 말끔하게" },
    { id: 21, title: "여궁화이트", url: "https://replyalba.com/pt/SNLg3ILPbd", subtitle: "밝고 환한 자신감을 위한 화이트닝 케어" },
    { id: 22, title: "올리모아", url: "https://replyalba.com/pt/C7qCzRVOZ8", subtitle: "흐트러진 바디라인을 살려주는 집중 솔루션" },
    { id: 23, title: "올리모아 2", url: "https://replyalba.com/pt/yN552PODWx", subtitle: "아름다운 몸매를 위한 스마트한 선택" },
    { id: 24, title: "우먼시크릿", url: "https://replyalba.com/pt/YfcVFCdD21", subtitle: "사랑받는 여자의 비밀, 지금 공개합니다" },
    { id: 25, title: "우먼시크릿2", url: "https://replyalba.com/pt/xWHMHU09mP", subtitle: "더 깊고 진한 사랑을 위한 시크릿 관리" },
    { id: 26, title: "우먼시크릿3", url: "https://replyalba.com/pt/LAiSP6X1ij", subtitle: "여성의 건강과 아름다움을 지키는 파트너" },
    { id: 27, title: "우먼시크릿4", url: "https://replyalba.com/pt/EkShEr1oPs", subtitle: "당신의 가치를 높여주는 프리미엄 솔루션" },
    { id: 28, title: "우먼시크릿5", url: "https://replyalba.com/pt/WSueAH6gko", subtitle: "남편 몰래 시작하는 놀라운 신체 변화" },
    { id: 29, title: "천수애진", url: "https://replyalba.com/pt/SanlazetIb", subtitle: "마시는 고함량 콜라겐으로 탱탱한 피부 재생" },
    { id: 30, title: "천수애진2", url: "https://replyalba.com/pt/PkcJmotCli", subtitle: "속부터 채워지는 윤기와 보습의 결정체" },
    { id: 31, title: "천수윤진", url: "https://replyalba.com/pt/ILAPhWg9Zx", subtitle: "국내 최초 '녹용 줄기세포 배양액' 함유 앰플" },
    { id: 32, title: "천수윤진2", url: "https://replyalba.com/pt/Sxw8G15GMU", subtitle: "바를수록 어려지는 기적의 피부 솔루션" },
];
